version: '3.8'
services:
  db:
    image: postgres:14
    container_name: pagepolly_postgres
    environment:
      POSTGRES_USER: pagepolly_webzucht
      POSTGRES_PASSWORD: H33l-L@ng!!-WW
      POSTGRES_DB: pagepolly
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
